# Generated by Django 4.0.1 on 2022-02-08 10:38

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('videoFile', models.FileField(null=True, upload_to='videos/', validators=[main.validators.validate_file_ext], verbose_name='')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
