# Generated by Django 4.0.1 on 2022-02-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('frameFile', models.FileField(upload_to='frames/')),
                ('frameNum', models.IntegerField()),
            ],
        ),
    ]
