# Generated by Django 4.0.1 on 2022-02-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresize',
            name='x2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='videoresize',
            name='y2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='videoresize',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='videoresize',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='videoresize',
            name='x1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='videoresize',
            name='y1',
            field=models.FloatField(null=True),
        ),
    ]
