# Generated by Django 4.0.1 on 2022-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frameFile',
            field=models.ImageField(upload_to='frames/'),
        ),
    ]
