# Generated by Django 4.0.1 on 2022-02-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_frame_userid_alter_video_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='userId',
            new_name='user',
        ),
    ]
